# Generated by Django 4.1.3 on 2022-12-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=255)),
                ('is_request_processed', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternetPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=50, verbose_name='Plan name')),
                ('speed', models.CharField(max_length=20, verbose_name='Speed Mbps')),
                ('price', models.FloatField(verbose_name='Monthly price in NIS')),
            ],
            options={
                'verbose_name': 'Internet Package',
                'verbose_name_plural': 'Internet Packages',
            },
        ),
    ]
