# Generated by Django 4.1.3 on 2022-11-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internetplans',
            options={'verbose_name': 'Internet Package', 'verbose_name_plural': 'Internet Packages'},
        ),
        migrations.AlterField(
            model_name='internetplans',
            name='planName',
            field=models.CharField(max_length=50, verbose_name='Plan name'),
        ),
        migrations.AlterField(
            model_name='internetplans',
            name='price',
            field=models.FloatField(verbose_name='Monthly price in NIS'),
        ),
        migrations.AlterField(
            model_name='internetplans',
            name='speed',
            field=models.CharField(max_length=20, verbose_name='Speed Mbps'),
        ),
    ]
